const GET_REQUEST = "GET_REQUEST";
const GET_ERROR = "GET_ERROR";
const GET_SUCCESS = "GET_SUCCESS";
const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const CART_ADD_ITEM = "CART_ADD_ITEM";
const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export {
  GET_ERROR,
  GET_REQUEST,
  GET_SUCCESS,
  USER_SIGNIN,
  USER_SIGNOUT,
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
};
